### ISSUE TITLE
design: 런치스크린, 세팅 뷰 수정

### ISSUE THREAD

**Issue by sumintnals** [PIM-PillReminder/PIM#13]
- [x] 런치스크린 넣기
- [x] 세팅 뷰 수정
![image](https://github.com/PIM-PillReminder/PIM/assets/127755029/ce8705be-02ff-4ad9-81e3-74ea77f0dc6d)

끝난 다음 할 일...
- [ ] 캘린더 공부하기 💀

**Comment by MADElinessss** [comment]
+ 세팅뷰에서 알림 활성화하는 코드 추가!
-> LocalNotificationManager 파일에 주석 참고 🐥

**Comment by sumintnals** [comment]
![Simulator Screenshot - iPhone 14 - 2023-09-27 at 16 55 26](https://github.com/PIM-PillReminder/PIM/assets/127755029/037cc9ca-d906-4f05-bd26-dd927fa9e689)
일단 뷰는 완성 ^_^ 기능은 나중에 연결...
