### ISSUE TITLE
feat: SettingView 구현

### ISSUE THREAD

**Issue by sumintnals** [PIM-PillReminder/PIM#2]
![image](https://github.com/PIM-PillReminder/PIM/assets/127755029/6072707a-1e60-4ba8-889a-2f8515e45922)

- [x] Setting View 만들기

- [x] Noti Setting View 만들기

---
2023.09.20 추가...

- [x] 사용하지 않는 뷰/버튼 비활성화 시키기

- [ ] 드롭다운 피커 고치기

- [ ] 알림 강도 구현

~~- [ ] 전화 알림 구현~~

- [x] 기본 리스트 사용할 것인지, 전체 커스텀 할 것인지? -> 패딩 조절, 전체 간격 조절, 라디우스 조절 시도하고  안되면 커스텀하기!

**Comment by Miiirona** [comment]
세팅뷰에서 지금 필요한 게 1. 복용시간 설정 2. 알림 기능 설정 인데, 약 종류 데이터백업 잠금 등 지금 필요없는 건 만들어놓고 비활성화해놓는 게 나을지 아니면 지금 쓸 것만 띄우는 게 나을지??

**Comment by sumintnals** [comment]
둘다 괜찮을 것 같은데 @_@ 일단 기능 없이 만들어만 둘까요!?

**Comment by Miiirona** [comment]
넹!! 같은 주제로 피그마 댓글도 있숩니당!

**Comment by sumintnals** [comment]
현재 이것저것 참고해서 드롭다운 커스텀 피커를 만들고 있는데 잘 안되네요 ㅠㅠ... 뭘 누르든지 약하게로 바뀌는... 
또 기본 리스트를 사용해서 뷰를 그렸는데, 코너라디우스와 구분선 스타일이 달라서 전체 커스텀으로 가야할지 고민중입니다... 💀💀💀💀
<img width="296" alt="image" src="https://github.com/PIM-PillReminder/PIM/assets/127755029/77c7f53c-6d81-41c0-9999-abf476c0127f">

기능 구현도 안된 상태에요... ㅠㅠㅠㅠ(알림 강도, 전화 알림)

**Comment by sumintnals** [comment]
리스트 커스텀 -> (제 서치력과 실력의 문제일수도 있음)안되는 듯 합니다... 혹시나 리스트로 할 수 있는 방법을 알게 된다면 알려주세요 T.T
그룹박스 커스텀 -> 시도중... 💀💀

**Comment by sumintnals** [comment]
그룹박스로 커스텀 완료
이제 남은거
알람 빈도 정하는 방법(슬라이더? 피커?) 정해지는 대로 만들기
비활성화 된 부분 누르면 어떻게 알려줄지 고민하기...
알림은 나중에 연결하기!
